version: '3'

services:
  drupal:
    build:
      # dockerfile: Dockerfile
      context: .
    container_name: custom-drupal
    image: TheSaviourEking/custom-drupal
    ports:
      - "8080:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=value
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
